import {
  Briefcase,
  CalendarCheck2,
  CalendarIcon,
  Check,
  CheckCircle,
  ChevronDown,
  CircleDashed,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileIcon,
  Lock,
  LogOut,
  Mail,
  MoreVertical,
  Newspaper,
  Phone,
  Plus,
  Settings,
  SquarePen,
  Trash,
  User,
  UserRoundXIcon,
  Users,
  X,
} from 'lucide-react';

export const Icons = {
  eye: Eye,
  eyeOff: EyeOff,
  setting: Settings,
  user: User,
  users: Users,
  logout: LogOut,
  briefcase: Briefcase,
  calendar: CalendarIcon,
  action: MoreVertical,
  plus: Plus,
  mail: Mail,
  phone: Phone,
  file: FileIcon,
  x: X,
  calendarCheck: CalendarCheck2,
  userRoundX: UserRoundXIcon,
  circleDashed: CircleDashed,
  checkCircle: CheckCircle,
  download: Download,
  trash: Trash,
  edit: SquarePen,
  lock: Lock,
  link: ExternalLink,
  chevronDown: ChevronDown,
  paper: Newspaper,
  check: Check,
};
